compatibility_date = "2024-09-20"  # 添加 compatibility_date
name = "cloudflare-docker-proxy"  # 指定 Worker 名称
main = "src/index.js" # 添加入口文件路径

[env.production]
routes = [
  { pattern = "docker.dockerray0606.org", custom_domain = true },
  { pattern = "quay.dockerray0606.org", custom_domain = true },
  { pattern = "gcr.dockerray0606.org", custom_domain = true },
  { pattern = "k8s-gcr.dockerray0606.org", custom_domain = true },
  { pattern = "k8s.dockerray0606.org", custom_domain = true },
  { pattern = "ghcr.dockerray0606.org", custom_domain = true },
  { pattern = "cloudsmith.dockerray0606.org", custom_domain = true }
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = "https://upstream.server.url"

[env.staging]
name = "cloudflare-docker-proxy-staging"  # 添加 staging 环境的名称
route = { pattern = "docker-staging.dockerray0606.org", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = "https://staging-upstream.server.url"
