# 默认的入口文件，可以根据你的项目路径调整
main = "src/index.js"  # 你项目中的入口文件

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.dockerray0606.org", custom_domain = true },
  { pattern = "quay.dockerray0606.org", custom_domain = true },
  { pattern = "gcr.dockerray0606.org", custom_domain = true },
  { pattern = "k8s-gcr.dockerray0606.org", custom_domain = true },
  { pattern = "k8s.dockerray0606.org", custom_domain = true },
  { pattern = "ghcr.dockerray0606.org", custom_domain = true },
  { pattern = "cloudsmith.dockerray0606.org", custom_domain = true }
]

[env.production.vars]
MODE = "production"
# 确保 TARGET_UPSTREAM 设置为正确的 URL 或 IP 地址，或者删除它
TARGET_UPSTREAM = "https://upstream.server.url"

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.dockerray0606.org", custom_domain = true }

[env.staging.vars]
MODE = "staging"
# 同样为 staging 环境定义 TARGET_UPSTREAM
TARGET_UPSTREAM = "https://staging-upstream.server.url"
