# 顶层定义 compatibility_date 和 main
compatibility_date = "2024-09-20"
main = "src/index.js"  # 入口文件路径

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.dockerray0606.org", custom_domain = true },
  { pattern = "quay.dockerray0606.org", custom_domain = true },
  { pattern = "gcr.dockerray0606.org", custom_domain = true },
  { pattern = "k8s-gcr.dockerray0606.org", custom_domain = true },
  { pattern = "k8s.dockerray0606.org", custom_domain = true },
  { pattern = "ghcr.dockerray0606.org", custom_domain = true },
  { pattern = "cloudsmith.dockerray0606.org", custom_domain = true }
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = "https://upstream.server.url"

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.dockerray0606.org", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = "https://staging-upstream.server.url"
