name: Deploy to Cloudflare Workers (Staging)

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # 更新为 CLOUDFLARE_API_TOKEN
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # 更新为 CLOUDFLARE_ACCOUNT_ID
          command: deploy --env staging --minify src/index.js
          environment: staging
